import "./js/enterModal"
import "./js/header";
import "./js/gamesList";
import "./js/gameRSP";
import "./js/yobc";
import "./js/GTNTCG";
import "./js/calculator";
import "./js/timeCalculator";
import "./js/dino";
import "./js/footer";
